// Central place for the user-facing strings of the graph view.

export const TOOLBAR_STRINGS = {
  hideCto: '◀ CTO',
  showCto: '▶ CTO',
  hideCtoTooltip: 'Hide CTO text',
  showCtoTooltip: 'Show CTO text',
  importLabel: 'Import',
  pasteImportLabel: 'Paste JSON',
  pasteImportTooltip: 'Import metamodel JSON by pasting it',
  exportLabel: 'Export',
  addDeclaration: '+ Add',
  undoIcon: '↩',
  redoIcon: '↪',
  undoTooltip: 'Undo (Ctrl+Z)',
  redoTooltip: 'Redo (Ctrl+Shift+Z)',
  searchIcon: '⌕',
  searchNodes: 'Search nodes',
  searchTooltip: 'Search nodes (Ctrl+K)',
  searchKbdHint: '⌘K',
  legendProperty: 'property',
  legendRelationship: 'relationship',
  legendExtends: 'extends',
} as const;

export const DIALOG_STRINGS = {
  addDeclarationTitle: 'Add Declaration',
  declarationNamePlaceholder: 'Name (e.g. MyContract)',
  extendsPrimitiveLabel: 'Extends primitive',
  mapKeyTypeLabel: 'Key Type',
  mapValueTypeLabel: 'Value Type',
  addPropertyTitle: (declName: string) => `Add Property to ${declName}`,
  propertyNamePlaceholder: 'Property name',
  optionalLabel: 'optional',
  arrayLabel: 'array []',
  relationshipLabel: 'relationship (-->)',
  addEnumValueTitle: (declName: string) => `Add Value to ${declName}`,
  enumValuePlaceholder: 'Value (e.g. Active)',
  setInheritanceTitle: (declName: string) => `Set Inheritance for ${declName}`,
  noInheritanceOption: 'None (no inheritance)',
  add: 'Add',
  set: 'Set',
  cancel: 'Cancel',
  pasteImportTitle: 'Import Metamodel JSON',
  pasteImportPlaceholder: 'Paste a Concerto metamodel JSON AST here (single Model or a { models: [...] } container)…',
  pasteImportSubmit: 'Import',
  pasteImportBusy: 'Importing…',
} as const;

export const SEARCH_STRINGS = {
  icon: '⌕',
  placeholder: 'Search declarations and properties…',
  escHint: 'ESC',
  noMatches: (query: string) => `No matches for “${query}”`,
  emptyHint: 'Search by declaration or property name.',
} as const;
