/**
 * Concerto code generation wrapper.
 *
 * Attempts to use the real @accordproject/concerto-core + concerto-codegen
 * packages for live generation. Falls back to pre-generated static samples
 * if bundling or parsing fails, so the playground always shows meaningful output.
 */

export type TargetLanguage =
  | "typescript"
  | "jsonschema"
  | "python"
  | "java"
  | "go"
  | "openapi";

export interface GenerationResult {
  output: string;
  isLive: boolean; // true = generated from the actual model; false = static fallback
  error?: string;
}

// ── Live generation ──────────────────────────────────────────────────────────

async function generateLive(
  ctoSource: string,
  target: TargetLanguage,
): Promise<string> {
  // Dynamic imports so Vite can tree-shake if bundling fails
  const { ModelManager } = await import("@accordproject/concerto-core");
  const { CodeGen } = await import("@accordproject/concerto-codegen");
  const { InMemoryWriter } = await import("@accordproject/concerto-util");

  const modelManager = new ModelManager();
  modelManager.addCTOModel(ctoSource, "input.cto", true);
  await modelManager.updateExternalModels();

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const visitorMap: Partial<Record<TargetLanguage, new () => any>> = {
    typescript: CodeGen.TypescriptVisitor,
    jsonschema: CodeGen.JSONSchemaVisitor,
    java: CodeGen.JavaVisitor,
    go: CodeGen.GoLangVisitor,
    openapi: CodeGen.OpenApiVisitor,
  };

  const VisitorClass = visitorMap[target];
  if (!VisitorClass) throw new Error(`No live visitor for target: ${target}`);
  const writer = new InMemoryWriter();
  const visitor = new VisitorClass();
  visitor.visit(modelManager, { fileWriter: writer });

  const files: Map<string, string> = writer.getFilesInMemory();
  const parts: string[] = [];
  for (const [fileName, content] of files) {
    parts.push(`// ${fileName}\n${content}`);
  }
  return parts.join("\n\n");
}

// ── Static fallbacks (always correct for the NDA example) ───────────────────

const STATIC: Record<TargetLanguage, string> = {
  typescript: `// Generated by Concerto — org.accordproject.nda@1.0.0

export enum GoverningLaw {
   NEW_YORK = 'NEW_YORK',
   CALIFORNIA = 'CALIFORNIA',
   DELAWARE = 'DELAWARE',
   ENGLAND_AND_WALES = 'ENGLAND_AND_WALES',
}

export interface Party {
   name: string;
   email: string;
   registeredAddress?: string;
}

export interface NDAData {
   disclosingParty: Party;
   receivingParty: Party;
   effectiveDate: Date;
   termMonths: number;
   governingLaw: GoverningLaw;
   permittedPurposes?: string[];
   includeNonSolicitation: boolean;
}`,

  jsonschema: `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "org.accordproject.nda@1.0.0.GoverningLaw": {
      "title": "GoverningLaw",
      "type": "string",
      "enum": ["NEW_YORK", "CALIFORNIA", "DELAWARE", "ENGLAND_AND_WALES"]
    },
    "org.accordproject.nda@1.0.0.Party": {
      "title": "Party",
      "type": "object",
      "required": ["name", "email"],
      "properties": {
        "name": { "type": "string" },
        "email": { "type": "string" },
        "registeredAddress": { "type": "string" }
      },
      "additionalProperties": false
    },
    "org.accordproject.nda@1.0.0.NDAData": {
      "title": "NDAData",
      "type": "object",
      "required": ["disclosingParty", "receivingParty", "effectiveDate", "termMonths", "governingLaw"],
      "properties": {
        "disclosingParty": { "$ref": "#/definitions/org.accordproject.nda@1.0.0.Party" },
        "receivingParty": { "$ref": "#/definitions/org.accordproject.nda@1.0.0.Party" },
        "effectiveDate": { "type": "string", "format": "date-time" },
        "termMonths": { "type": "integer" },
        "governingLaw": { "$ref": "#/definitions/org.accordproject.nda@1.0.0.GoverningLaw" },
        "permittedPurposes": { "type": "array", "items": { "type": "string" } },
        "includeNonSolicitation": { "type": "boolean", "default": false }
      },
      "additionalProperties": false
    }
  }
}`,

  python: `# Generated by Concerto — org.accordproject.nda@1.0.0
from __future__ import annotations
from datetime import datetime
from enum import Enum
from typing import List, Optional
from pydantic import BaseModel


class GoverningLaw(str, Enum):
    NEW_YORK = "NEW_YORK"
    CALIFORNIA = "CALIFORNIA"
    DELAWARE = "DELAWARE"
    ENGLAND_AND_WALES = "ENGLAND_AND_WALES"


class Party(BaseModel):
    name: str
    email: str
    registered_address: Optional[str] = None


class NDAData(BaseModel):
    disclosing_party: Party
    receiving_party: Party
    effective_date: datetime
    term_months: int
    governing_law: GoverningLaw
    permitted_purposes: Optional[List[str]] = None
    include_non_solicitation: bool = False`,

  java: `// Generated by Concerto — org.accordproject.nda@1.0.0
package org.accordproject.nda;

import java.util.Date;
import java.util.List;

public enum GoverningLaw {
    NEW_YORK, CALIFORNIA, DELAWARE, ENGLAND_AND_WALES
}

// Party.java
public class Party {
    private String name;
    private String email;
    private String registeredAddress; // optional

    public Party() {}

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }
    public String getEmail() { return email; }
    public void setEmail(String email) { this.email = email; }
    public String getRegisteredAddress() { return registeredAddress; }
    public void setRegisteredAddress(String registeredAddress) { this.registeredAddress = registeredAddress; }
}

// NDAData.java
public class NDAData {
    private Party disclosingParty;
    private Party receivingParty;
    private Date effectiveDate;
    private int termMonths;
    private GoverningLaw governingLaw;
    private List<String> permittedPurposes; // optional
    private boolean includeNonSolicitation = false;

    public Party getDisclosingParty() { return disclosingParty; }
    public void setDisclosingParty(Party disclosingParty) { this.disclosingParty = disclosingParty; }
    public Party getReceivingParty() { return receivingParty; }
    public void setReceivingParty(Party receivingParty) { this.receivingParty = receivingParty; }
    public Date getEffectiveDate() { return effectiveDate; }
    public void setEffectiveDate(Date effectiveDate) { this.effectiveDate = effectiveDate; }
    public int getTermMonths() { return termMonths; }
    public void setTermMonths(int termMonths) { this.termMonths = termMonths; }
    public GoverningLaw getGoverningLaw() { return governingLaw; }
    public void setGoverningLaw(GoverningLaw governingLaw) { this.governingLaw = governingLaw; }
    public List<String> getPermittedPurposes() { return permittedPurposes; }
    public void setPermittedPurposes(List<String> permittedPurposes) { this.permittedPurposes = permittedPurposes; }
    public boolean isIncludeNonSolicitation() { return includeNonSolicitation; }
    public void setIncludeNonSolicitation(boolean includeNonSolicitation) { this.includeNonSolicitation = includeNonSolicitation; }
}`,

  go: `// Generated by Concerto — org.accordproject.nda@1.0.0
package nda

import "time"

type GoverningLaw string

const (
	GoverningLawNewYork         GoverningLaw = "NEW_YORK"
	GoverningLawCalifornia      GoverningLaw = "CALIFORNIA"
	GoverningLawDelaware        GoverningLaw = "DELAWARE"
	GoverningLawEnglandAndWales GoverningLaw = "ENGLAND_AND_WALES"
)

type Party struct {
	Name               string  \`json:"name"\`
	Email              string  \`json:"email"\`
	RegisteredAddress  *string \`json:"registeredAddress,omitempty"\`
}

type NDAData struct {
	DisclosingParty        Party        \`json:"disclosingParty"\`
	ReceivingParty         Party        \`json:"receivingParty"\`
	EffectiveDate          time.Time    \`json:"effectiveDate"\`
	TermMonths             int          \`json:"termMonths"\`
	GoverningLaw           GoverningLaw \`json:"governingLaw"\`
	PermittedPurposes      []string     \`json:"permittedPurposes,omitempty"\`
	IncludeNonSolicitation bool         \`json:"includeNonSolicitation"\`
}`,

  openapi: `# Generated by Concerto — org.accordproject.nda@1.0.0
openapi: 3.0.0
info:
  title: NDA API
  version: 1.0.0
components:
  schemas:
    GoverningLaw:
      type: string
      enum:
        - NEW_YORK
        - CALIFORNIA
        - DELAWARE
        - ENGLAND_AND_WALES
    Party:
      type: object
      required:
        - name
        - email
      properties:
        name:
          type: string
        email:
          type: string
        registeredAddress:
          type: string
    NDAData:
      type: object
      required:
        - disclosingParty
        - receivingParty
        - effectiveDate
        - termMonths
        - governingLaw
      properties:
        disclosingParty:
          $ref: '#/components/schemas/Party'
        receivingParty:
          $ref: '#/components/schemas/Party'
        effectiveDate:
          type: string
          format: date-time
        termMonths:
          type: integer
        governingLaw:
          $ref: '#/components/schemas/GoverningLaw'
        permittedPurposes:
          type: array
          items:
            type: string
        includeNonSolicitation:
          type: boolean
          default: false`,
};

// ── Public API ───────────────────────────────────────────────────────────────

export async function generate(
  ctoSource: string,
  target: TargetLanguage,
): Promise<GenerationResult> {
  try {
    const output = await generateLive(ctoSource, target);
    return { output, isLive: true };
  } catch (liveError) {
    // Fall back to static output for the NDA example
    const fallback = STATIC[target];
    return {
      output: fallback,
      isLive: false,
      error:
        liveError instanceof Error ? liveError.message : String(liveError),
    };
  }
}
